/**
 * A6 章节表（E06b：mid / letters 分文件，数值不变）
 */
import {
  faceDefaults, midChapter, letterChapter,
} from '../_shared.js';
import {
  chapter_a6_mid_1,
  chapter_a6_mid_2,
  chapter_a6_mid_3,
  chapter_a6_mid_4,
  chapter_a6_midboss,
  chapter_a6_mid_5,
  chapter_a6_mid_6,
  chapter_a6_mid_7,
  chapter_a6_mid_8,
  chapter_a6_mid_9,
  chapter_a6_mid_10,
} from './mid.js';
import {
  chapter_yimeige_1,
  chapter_yimeige_2,
  chapter_yimeige_3,
  chapter_yimeige_4,
  chapter_yimeige_5,
  chapter_yimeige_6,
  chapter_yimeige_7,
  chapter_yimeige_8,
  chapter_yimeige_last,
} from './letters.js';

const FACE = faceDefaults('A6');

export const chapters = [
  midChapter(FACE, {
    id: 57,
    name: 'A6-1 乐园入口',
    kind: 'mid',
    unstable: true,
    duration: 24,
    build: chapter_a6_mid_1,
  }),
  midChapter(FACE, {
    id: 58,
    name: 'A6-2 Unstable 糖衣炮弹',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_a6_mid_2,
  }),
  midChapter(FACE, {
    id: 59,
    name: 'A6-3 甜腻迷雾',
    kind: 'mid',
    unstable: true,
    duration: 24,
    build: chapter_a6_mid_3,
  }),
  midChapter(FACE, {
    id: 60,
    name: 'A6-4 虚假善意',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_a6_mid_4,
  }),
  midChapter(FACE, {
    id: 61,
    name: 'A6-5 乐园守护者',
    kind: 'midboss',
    duration: 34,
    build: chapter_a6_midboss,
  }),
  midChapter(FACE, {
    id: 62,
    name: 'A6-6 甜蜜陷阱',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_a6_mid_5,
  }),
  midChapter(FACE, {
    id: 63,
    name: 'A6-7 乐园暗流',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_a6_mid_6,
  }),
  midChapter(FACE, {
    id: 64,
    name: 'A6-8 剧情裂痕',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_a6_mid_7,
  }),
  midChapter(FACE, {
    id: 65,
    name: 'A6-9 乐园崩坏前兆',
    kind: 'mid',
    unstable: true,
    duration: 30,
    build: chapter_a6_mid_8,
  }),
  midChapter(FACE, {
    id: 66,
    name: 'A6-10 真相浮现',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_a6_mid_9,
  }),
  midChapter(FACE, {
    id: 67,
    name: 'A6-11 最终层切入',
    kind: 'mid',
    unstable: true,
    duration: 30,
    build: chapter_a6_mid_10,
  }),
  letterChapter(FACE, {
    id: 68,
    name: '一美个「哈机密·甜蜜陷阱」',
    dialogue: 'a6',
    letter: '哈机密 · 甜蜜陷阱',
    letterTime: 42,
    build: chapter_yimeige_1,
  }),
  letterChapter(FACE, {
    id: 69,
    name: '一美个「哈机密·糖衣外交」',
    letter: '哈机密 · 糖衣外交',
    letterTime: 42,
    build: chapter_yimeige_2,
  }),
  letterChapter(FACE, {
    id: 70,
    name: '一美个「哈机密·言论审查」',
    letter: '哈机密 · 言论审查',
    letterTime: 44,
    build: chapter_yimeige_3,
  }),
  letterChapter(FACE, {
    id: 71,
    name: '一美个「哈机密·数据篡改」',
    letter: '哈机密 · 数据篡改',
    letterTime: 44,
    build: chapter_yimeige_4,
  }),
  letterChapter(FACE, {
    id: 72,
    name: '一美个「哈机密·伪装剥离」',
    letter: '哈机密 · 伪装剥离',
    letterTime: 46,
    build: chapter_yimeige_5,
  }),
  letterChapter(FACE, {
    id: 73,
    name: '一美个「哈机密·苦口婆心」',
    letter: '哈机密 · 苦口婆心',
    letterTime: 46,
    build: chapter_yimeige_6,
  }),
  letterChapter(FACE, {
    id: 74,
    name: '一美个「哈机密·层层剥落」',
    letter: '哈机密 · 层层剥落',
    letterTime: 48,
    build: chapter_yimeige_7,
  }),
  letterChapter(FACE, {
    id: 75,
    name: '一美个「哈机密乐园·全面崩坏」',
    dialogue: 'a6_last',
    letter: '哈机密乐园 · 全面崩坏',
    letterTime: 50,
    build: chapter_yimeige_8,
  }),
  letterChapter(FACE, {
    id: 76,
    name: '一美个「哈机密乐园·回收站清空」',
    letter: '回收站清空 · 最终抹消',
    letterTime: 55,
    ending: 'A',
    build: chapter_yimeige_last,
  }),
];

export const stageSelectEntry = { id: 'A6', label: 'A线6面', desc: '一美个 — 哈机密乐园崩坏', startChapter: 57 };
