/**
 * B6 章节表（E06b：mid / letters 分文件，数值不变）
 */
import {
  faceDefaults, midChapter, letterChapter,
} from '../_shared.js';
import {
  chapter_b6_mid_1,
  chapter_b6_mid_2,
  chapter_b6_mid_3,
  chapter_b6_mid_4,
  chapter_b6_midboss,
  chapter_b6_mid_5,
  chapter_b6_mid_6,
  chapter_b6_mid_7,
  chapter_b6_mid_8,
  chapter_b6_mid_9,
  chapter_b6_mid_10,
} from './mid.js';
import {
  chapter_lastgod_1,
  chapter_lastgod_2,
  chapter_lastgod_3,
  chapter_lastgod_4,
  chapter_lastgod_5,
  chapter_lastgod_6,
  chapter_lastgod_7,
  chapter_lastgod_8,
  chapter_lastgod_last,
} from './letters.js';

const FACE = faceDefaults('B6');

export const chapters = [
  midChapter(FACE, {
    id: 109,
    name: 'B6-1 迷雾边境',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_b6_mid_1,
  }),
  midChapter(FACE, {
    id: 110,
    name: 'B6-2 Unstable 防御塔阵列',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_b6_mid_2,
  }),
  midChapter(FACE, {
    id: 111,
    name: 'B6-3 炫妈气息',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_b6_mid_3,
  }),
  midChapter(FACE, {
    id: 112,
    name: 'B6-4 虾油迷雾',
    kind: 'mid',
    unstable: true,
    duration: 26,
    build: chapter_b6_mid_4,
  }),
  midChapter(FACE, {
    id: 113,
    name: 'B6-5 神炫祭司',
    kind: 'midboss',
    duration: 36,
    build: chapter_b6_midboss,
  }),
  midChapter(FACE, {
    id: 114,
    name: 'B6-6 宝瓶守护',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_b6_mid_5,
  }),
  midChapter(FACE, {
    id: 115,
    name: 'B6-7 王座之道',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_b6_mid_6,
  }),
  midChapter(FACE, {
    id: 116,
    name: 'B6-8 防空洞陷阱',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_b6_mid_7,
  }),
  midChapter(FACE, {
    id: 117,
    name: 'B6-9 风油精屏障',
    kind: 'mid',
    unstable: true,
    duration: 30,
    build: chapter_b6_mid_8,
  }),
  midChapter(FACE, {
    id: 118,
    name: 'B6-10 宝瓶封印解除',
    kind: 'mid',
    unstable: true,
    duration: 28,
    build: chapter_b6_mid_9,
  }),
  midChapter(FACE, {
    id: 119,
    name: 'B6-11 王座前震荡',
    kind: 'mid',
    unstable: true,
    duration: 32,
    build: chapter_b6_mid_10,
  }),
  letterChapter(FACE, {
    id: 120,
    name: '拉斯特神炫「炫妈迷雾·王座审判」',
    dialogue: 'b6',
    letter: '炫妈迷雾 · 王座审判',
    letterTime: 45,
    build: chapter_lastgod_1,
  }),
  letterChapter(FACE, {
    id: 121,
    name: '拉斯特神炫「炫妈迷雾·虾油侵蚀」',
    letter: '炫妈涂抹 · 虾油侵蚀',
    letterTime: 44,
    build: chapter_lastgod_2,
  }),
  letterChapter(FACE, {
    id: 122,
    name: '拉斯特神炫「炫妈迷雾·宝瓶泄露」',
    letter: '炫妈迷雾 · 宝瓶泄露',
    letterTime: 46,
    build: chapter_lastgod_3,
  }),
  letterChapter(FACE, {
    id: 123,
    name: '拉斯特神炫「炫妈迷雾·味道扩散」',
    letter: '炫妈迷雾 · 味道扩散',
    letterTime: 46,
    build: chapter_lastgod_4,
  }),
  letterChapter(FACE, {
    id: 124,
    name: '拉斯特神炫「炫妈迷雾·神之轻蔑」',
    letter: '炫妈迷雾 · 神之轻蔑',
    letterTime: 48,
    build: chapter_lastgod_5,
  }),
  letterChapter(FACE, {
    id: 125,
    name: '拉斯特神炫「炫妈迷雾·雾中獠牙」',
    letter: '炫妈迷雾 · 雾中獠牙',
    letterTime: 48,
    build: chapter_lastgod_6,
  }),
  letterChapter(FACE, {
    id: 126,
    name: '拉斯特神炫「炫妈迷雾·王座崩塌」',
    letter: '炫妈迷雾 · 王座崩塌',
    letterTime: 50,
    build: chapter_lastgod_7,
  }),
  letterChapter(FACE, {
    id: 127,
    name: '拉斯特神炫「虾油风油精·绝对帝国」',
    dialogue: 'b6_last',
    letter: '虾油风油精 · 绝对帝国',
    letterTime: 55,
    build: chapter_lastgod_8,
  }),
  letterChapter(FACE, {
    id: 128,
    name: '拉斯特神炫「虾油风油精·炫妈归天」',
    letter: '虾油风油精 · 炫妈归天',
    letterTime: 120,
    ending: 'B',
    build: chapter_lastgod_last,
  }),
];

export const stageSelectEntry = { id: 'B6', label: 'B线6面', desc: '拉斯特神炫 — 虾油风油精终局', startChapter: 109 };
